name: Update Output JSON & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/input.json'  # ✅ Trigger only when input.json changes
  workflow_dispatch:

permissions:
  contents: write  
  pages: write      
  id-token: write
     
jobs:
  update-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R  

      - name: Debug - Check if input.json exists
        run: |
          if [ ! -f src/input.json ]; then
            echo "❌ Error: input.json not found in src/"
            exit 1
          else
            echo "✅ input.json found!"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Output JSON
        run: node src/generateJson.cjs  # ✅ Run from correct path

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add src/Output.jsx
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Output.jsx"
          git push
        continue-on-error: true  

  build-and-deploy:
    needs: update-output  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4

      - name: Fetch Latest Changes (Ensure Updated Output.jsx)
        run: |
          git pull origin main  # ✅ Pull latest committed changes before building
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build  

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3   
        with:
          name: 'github-pages'
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'